language: elixir
elixir: '1.6.4'
otp_release: '20.0'
script:
  - mix test
  - mix coveralls.travis

deploy:
  provider: script
  script: $TRAVIS_BUILD_DIR/deploy.sh
  skip_cleanup: true
  on:
    branch: master
